export const API_ENDPOINTS = {
  SEND_OTP: "/user/send-otp",
  VERIFY_OTP: "/user/verify-otp",
  REFRESH_TOKEN: "/refresh",
  SIGNUP: "/user/signup",
  GET_STATES: "/get-states",
  GET_CITIES: "/get-cities",
  UPDATE_CURRENT_LOCATION: "/user/update-current-location",
  GET_PROFILE: "/user/get-profile",
  EDIT_PROFILE: "/edit-profile",

  GET_FEED: "/get-feed",
  LIKE: "/post/like",
  GET_COMMENTS: "/get-comments",
  GET_COMMENT_REPLIES: "/get-comment-replies",
  LIKE_COMMENT: "/comment/like",
  ADD_COMMENT: "/post/comment",
  ADD_COMMENT_REPLY: "/comment/reply",

  GET_RESTAURANTS: "/get-all-restaurants",
  GET_NEAREST_RESTAURANTS: "/get-nearest-restaurants",
  GET_UPCOMING_EVENTS: "/get-all-upcoming-events",
  GET_RESTAURANT_DETAILS: "/get-restaurant-details",
  GET_RESTAURANT_IMAGES: "/get-restaurant-images",
  GET_RESTAURANT_CALENDAR: "/get-restaurant-calendar",
  GET_RESTAURANT_PACKAGES: "/get-restaurant-packages",

  GET_RESTAURANT_BOOKINGS: "/get-restaurant-bookings",
  GET_TICKET_BOOKINGS: "/get-ticket-bookings",
  BOOK_EVENT_TICKETS: "/book-event-tickets",
  GET_OCCASIONS: "/get-occasions",
  RATE_RESTAURANT: "/rate-restaurant",
  BOOK_RESTAURANT_BANQUET: "/book-restaurant-banquet",
  APPLY_COUPON: "/apply-coupon",
  VERIFY_TICKET_PAYMENT: "/verify-ticket-payment",
  VERIFY_BANQUET_PAYMENT: "/verify-banquet-payment",
};
